### ISSUE TITLE
Should arrays be supported?

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/tailwind_merge#1]
cc https://github.com/dcastil/tailwind-merge/pull/127

**Comment by dcastil** [comment]
Awesome that you ported tailwind-merge to Ruby, love it!

Here's the reason why I added support for arrays in tailwind-merge:

Sometimes there are styles which only get applied with conditions. E.g. a button which gets some styles when it `isSomeVariant` and some more when it `isSomeVariant && isLarge`. Previously that would look like this:

```js
twMerge('…', isSomeVariant && '…', isSomeVariant && isLarge && '…')
```

The `isSomeVariant` condition needs to be duplicated for the second string. That's ok in this example but sometimes the condition can get more complex:

```js
twMerge(
    '…',
    someArray.length === 0 && !isNotSomeOtherVariant && '…',
    someArray.length === 0 && !isNotSomeOtherVariant && isLarge && '…'
)
```

It's easy to make mistakes here, especially if you need to change something about the condition in the future and forget to update the other condition. In the last example I'd probably move the condition `someArray.length === 0 && !isNotSomeOtherVariant` into a separate variable.

But this can be solved with an array as well which makes it possible to inline the variant condition while not needing to duplicate it.

```js
twMerge(
    '…',
    someArray.length === 0 && !isNotSomeOtherVariant && [
        '…',
        isLarge && '…'
    ]
)
```

**Comment by gjtorikian** [comment]
Hey hey! Thank you so much for building the original NPM package. I had been trying the same thing with some hideous regular expressions. 

As for me, I hit a performance issue with the way I was composing Tailwind classes as a string; I decided to just throw an Array at this gem instead. But, just now, I figured out a way to workaround my issue, so this is now less necessary for me.
