### ISSUE TITLE
Support for custom spacing

### ISSUE THREAD

**Issue by elalemanyo** [gjtorikian/tailwind_merge#31]
Hi, I love your gem, being able to do this in ruby helps me a lot with what I am building 🙏
I just have one question, which I may have missed the answer, sorry if that's the case. How do I add the [custom spacing](https://tailwindcss.com/docs/customizing-spacing) I am using?

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    spacing: {
      sm: '8px',
      md: '12px',
      lg: '16px',
      xl: '24px',
    }
  }
}
```

thanks and best regards

**Comment by gjtorikian** [comment]
Heya! I, uh, actually didn’t implement this. Here are all of the tests for such a feature, skipped: https://github.com/gjtorikian/tailwind_merge/blob/main/test/test_theme.rb

At the time of the gem’s writing, I didn’t have a need for theme conflict handling so I sort of avoided it. I’ll take a look in the next few days to actually incorporate this.
